# Generated by Django 3.1 on 2020-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetails',
            name='choice',
            field=models.CharField(choices=[('institute', 'INSTITUTE'), ('student', 'STUDENT')], default=None, max_length=10),
        ),
    ]
