# Generated by Django 3.1 on 2020-12-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0004_auto_20201206_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdetails',
            name='choice',
        ),
    ]
