# Generated by Django 3.1 on 2020-12-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0005_remove_otherdetails_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetails',
            name='choice',
            field=models.CharField(choices=[('institute', 'INSTITUTE'), ('student', 'STUDENT')], default='institute', max_length=10, null=True),
        ),
    ]
