# Generated by Django 3.1.2 on 2020-12-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0006_otherdetails_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submission',
            field=models.FileField(default='settings.MEDIA_ROOT/documents/SE Hackathon PS.pdf', max_length=254, upload_to='documents'),
        ),
    ]
