# Generated by Django 3.1.2 on 2020-12-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20201206_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_selected',
            name='pdf',
            field=models.FileField(default='settings.MEDIA_ROOT/documents/SE Hackathon PS.pdf', max_length=254, upload_to='documents'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
