# Generated by Django 3.1.2 on 2020-12-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20201206_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem_selected',
            name='s',
        ),
    ]
